import { ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DiligenciaWorkspace, VerificacionService } from '../../services/verificacion.service';

interface CapturaGps { estadoGps: 'DISPONIBLE'|'NO_AUTORIZADO'|'NO_DISPONIBLE'; latitud?: number; longitud?: number; }

@Component({selector:'app-diligencia',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./diligencia.html',styleUrl:'./diligencia.css'})
export class DiligenciaComponent implements OnInit,OnDestroy {
  programacionId=0; w:DiligenciaWorkspace|null=null; cargando=true; iniciando=false; guardando=false; finalizando=false;
  error=''; aviso=''; gpsMensaje='';
  situacionPersona='PENDIENTE'; personaNombres=''; personaApellidos=''; personaTipoDocumento=''; personaNumeroDocumento=''; personaCondicion='TITULAR'; personaObservaciones='';
  hechosConstatados=''; ocurrencias=''; observacionesFiscalizador=''; observacionesFiscalizado='';
  participanteTipo='PERSONAL_MUNICIPAL'; participanteNombre=''; participanteApellidos=''; participanteDocumentoTipo=''; participanteDocumento=''; participanteEntidad=''; participanteCargo=''; participanteObs=''; agregandoParticipante=false;
  evidenciaTipo='FOTO'; evidenciaDescripcion=''; evidenciaArchivo:File|null=null; evidenciaPreview=''; subiendoEvidencia=false;
  motivoNoRealizada='ADMINISTRADO_AUSENTE'; detalleMotivo=''; obsNoRealizada=''; registrandoNoRealizada=false;
  firmaEstado='FIRMA_PENDIENTE'; observacionFirma=''; copiaEntregada=false; medioEntrega='PENDIENTE';
  private saveTimer:ReturnType<typeof setTimeout>|null=null; private readonly delaySaveMs=550;

  constructor(private route:ActivatedRoute,private api:VerificacionService,private cdr:ChangeDetectorRef){}
  ngOnInit():void{this.programacionId=Number(this.route.snapshot.paramMap.get('programacionId'));void this.cargar();}
  ngOnDestroy():void{if(this.saveTimer)clearTimeout(this.saveTimer);if(this.evidenciaPreview)URL.revokeObjectURL(this.evidenciaPreview);}
  get puedeEditar():boolean{return !!this.w?.id&&['INICIADA','EN_DESARROLLO'].includes(this.w.estadoDiligencia||'');}
  get finalizada():boolean{return ['FINALIZADA','NO_REALIZADA'].includes(this.w?.estadoDiligencia||'');}
  get puedeMarcarIdentidad():boolean{return this.situacionPersona==='IDENTIFICADA';}
  async cargar():Promise<void>{this.cargando=true;this.error='';try{this.w=await this.api.obtenerEspacioDiligencia(this.programacionId);this.cargarCampos();}catch(e:any){this.error=e?.error?.message||'No se pudo cargar la programación asignada.';}finally{this.cargando=false;this.cdr.markForCheck();}}
  private cargarCampos():void{if(!this.w)return;this.situacionPersona=this.w.situacionPersona||'PENDIENTE';this.personaNombres=this.w.personaNombres||'';this.personaApellidos=this.w.personaApellidos||'';this.personaTipoDocumento=this.w.personaTipoDocumento||'';this.personaNumeroDocumento=this.w.personaNumeroDocumento||'';this.personaCondicion=this.w.personaCondicion||'TITULAR';this.personaObservaciones=this.w.personaObservaciones||'';this.hechosConstatados=this.w.hechosConstatados||'';this.ocurrencias=this.w.ocurrencias||'';this.observacionesFiscalizador=this.w.observacionesFiscalizador||'';this.observacionesFiscalizado=this.w.observacionesFiscalizado||'';this.motivoNoRealizada=this.w.motivoNoRealizada||'ADMINISTRADO_AUSENTE';this.detalleMotivo=this.w.detalleMotivoNoRealizada||'';this.copiaEntregada=this.w.copiaEntregada;this.medioEntrega=this.w.medioEntrega||'PENDIENTE';this.cdr.markForCheck();}
  async iniciar():Promise<void>{this.iniciando=true;this.error='';this.gpsMensaje='Solicitando ubicación del dispositivo…';this.cdr.markForCheck();try{const gps=await this.capturarGps();this.w=await this.api.iniciarDiligencia(this.programacionId,{...gps});this.cargarCampos();this.gpsMensaje=gps.estadoGps==='DISPONIBLE'?'Ubicación GPS de inicio registrada.':gps.estadoGps==='NO_AUTORIZADO'?'GPS no autorizado; la diligencia puede continuar.':'GPS no disponible; la diligencia puede continuar.';}catch(e:any){this.error=e?.error?.message||'No se pudo iniciar la diligencia.';}finally{this.iniciando=false;this.cdr.markForCheck();}}
  datos():Record<string,unknown>{return{situacionPersona:this.situacionPersona,personaNombres:this.personaNombres,personaApellidos:this.personaApellidos,personaTipoDocumento:this.personaTipoDocumento,personaNumeroDocumento:this.personaNumeroDocumento,personaCondicion:this.personaCondicion,personaObservaciones:this.personaObservaciones,hechosConstatados:this.hechosConstatados,ocurrencias:this.ocurrencias,observacionesFiscalizador:this.observacionesFiscalizador,observacionesFiscalizado:this.observacionesFiscalizado};}
  cambio():void{if(!this.puedeEditar)return;if(this.saveTimer)clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>void this.guardar(false),this.delaySaveMs);}
  async guardar(mostrar=true):Promise<boolean>{if(!this.puedeEditar||!this.w?.id)return false;if(this.guardando){if(this.saveTimer)clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>void this.guardar(false),250);return false;}if(this.saveTimer){clearTimeout(this.saveTimer);this.saveTimer=null;}this.guardando=true;this.error='';let ok=false;const id=this.w.id;const sent=JSON.stringify(this.datos());try{const response=await this.api.guardarDiligencia(id,this.datos());this.w={...this.w,estadoDiligencia:response.estadoDiligencia,estadoProgramacion:response.estadoProgramacion,fechaCierre:response.fechaCierre};if(mostrar)this.aviso='Avance guardado en el sistema.';ok=true;if(sent!==JSON.stringify(this.datos()))this.saveTimer=setTimeout(()=>void this.guardar(false),100);}catch(e:any){this.error=e?.error?.message||'No se pudo guardar el avance. Comprueba tu conexión e inténtalo de nuevo.';}finally{this.guardando=false;this.cdr.markForCheck();}return ok;}
  async agregarParticipante():Promise<void>{if(!this.w?.id)return;this.agregandoParticipante=true;this.error='';try{await this.api.agregarParticipanteDiligencia(this.w.id,{tipoParticipante:this.participanteTipo,nombre:this.participanteNombre,apellidos:this.participanteApellidos,tipoDocumento:this.participanteDocumentoTipo,numeroDocumento:this.participanteDocumento,entidadArea:this.participanteEntidad,cargoCondicion:this.participanteCargo,observaciones:this.participanteObs});await this.cargar();this.participanteNombre='';this.participanteApellidos='';this.participanteDocumentoTipo='';this.participanteDocumento='';this.participanteEntidad='';this.participanteCargo='';this.participanteObs='';this.aviso='Participante agregado.';}catch(e:any){this.error=e?.error?.message||'No se pudo agregar al participante.';}finally{this.agregandoParticipante=false;this.cdr.markForCheck();}}
  seleccionarEvidencia(event:Event):void{if(this.evidenciaPreview)URL.revokeObjectURL(this.evidenciaPreview);this.evidenciaArchivo=(event.target as HTMLInputElement).files?.[0]||null;this.evidenciaPreview=this.evidenciaArchivo&&this.evidenciaArchivo.type.startsWith('image/')?URL.createObjectURL(this.evidenciaArchivo):'';}
  async subirEvidencia():Promise<void>{if(!this.w?.id||!this.evidenciaArchivo)return;this.subiendoEvidencia=true;this.error='';try{if(!await this.guardar(false))throw new Error(this.error||'Guarda los cambios antes de adjuntar evidencia.');await this.api.agregarEvidenciaDiligencia(this.w.id,this.evidenciaTipo,this.evidenciaDescripcion,this.evidenciaArchivo);this.evidenciaArchivo=null;this.evidenciaDescripcion='';if(this.evidenciaPreview)URL.revokeObjectURL(this.evidenciaPreview);this.evidenciaPreview='';this.aviso='Evidencia adjuntada.';await this.cargar();}catch(e:any){this.error=e?.error?.message||e?.message||'No se pudo adjuntar la evidencia.';}finally{this.subiendoEvidencia=false;this.cdr.markForCheck();}}
  async abrirEvidencia(id:number,nombre:string):Promise<void>{if(!this.w?.id)return;try{const blob=await this.api.evidenciaDiligencia(this.w.id,id);this.descargar(blob,nombre);}catch{this.error='No se pudo abrir la evidencia.';}}
  async abrirSustento():Promise<void>{try{const blob=await this.api.documentoSustentoProgramacion(this.programacionId);this.descargar(blob,this.w?.documentoSustentoNombre||'Documento-sustento.pdf');}catch(e:any){this.error=e?.error?.message||'No se pudo abrir el documento de sustento.';}}
  async noRealizada():Promise<void>{this.registrandoNoRealizada=true;this.error='';try{const gps=await this.capturarGps();this.w=await this.api.noRealizadaDiligencia(this.programacionId,{motivo:this.motivoNoRealizada,detalleMotivo:this.detalleMotivo,observacionesFiscalizador:this.obsNoRealizada,estadoGps:gps.estadoGps,latitud:gps.latitud,longitud:gps.longitud});this.cargarCampos();this.aviso='La visita quedó registrada como NO REALIZADA. El expediente permanece abierto.';}catch(e:any){this.error=e?.error?.message||'No se pudo registrar la visita.';}finally{this.registrandoNoRealizada=false;this.cdr.markForCheck();}}
  async finalizar():Promise<void>{if(!this.w?.id)return;if(!await this.guardar(false))return;this.finalizando=true;this.error='';try{const gps=await this.capturarGps();await this.api.finalizarDiligencia(this.w.id,{firmaFiscalizado:this.firmaEstado,observacionFirma:this.observacionFirma,copiaEntregada:this.copiaEntregada,medioEntrega:this.medioEntrega,estadoGpsCierre:gps.estadoGps,latitudCierre:gps.latitud,longitudCierre:gps.longitud});this.aviso='Diligencia finalizada. Acta generada y expediente enviado a PENDIENTE_REVISION.';await this.cargar();}catch(e:any){this.error=e?.error?.message||'No se pudo finalizar la diligencia.';}finally{this.finalizando=false;this.cdr.markForCheck();}}
  async descargarActa():Promise<void>{if(!this.w?.acta)return;try{const blob=await this.api.descargarActa(this.w.acta.id);this.descargar(blob,this.w.acta.pdfGeneradoNombre);}catch(e:any){this.error=e?.error?.message||'No se pudo descargar el acta.';}}
  async subirCopiaFirmada(event:Event):Promise<void>{if(!this.w?.acta)return;const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.type!=='application/pdf'||!file.name.toLowerCase().endsWith('.pdf')){this.error='La copia firmada debe ser un PDF.';return;}try{await this.api.subirCopiaFirmadaActa(this.w.acta.id,file);this.aviso='Copia firmada agregada por separado al PDF generado.';await this.cargar();}catch(e:any){this.error=e?.error?.message||'No se pudo subir la copia firmada.';}this.cdr.markForCheck();}
  private capturarGps():Promise<CapturaGps>{return new Promise(resolve=>{if(!navigator.geolocation){resolve({estadoGps:'NO_DISPONIBLE'});return;}navigator.geolocation.getCurrentPosition(p=>resolve({estadoGps:'DISPONIBLE',latitud:p.coords.latitude,longitud:p.coords.longitude}),e=>resolve({estadoGps:e.code===1?'NO_AUTORIZADO':'NO_DISPONIBLE'}),{enableHighAccuracy:true,timeout:9000,maximumAge:0});});}
  private descargar(blob:Blob,nombre:string):void{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  formatoFecha(v:string|null):string{return v?new Intl.DateTimeFormat('es-PE',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Lima'}).format(new Date(v)):'';}
}
