import { ChangeDetectorRef, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AgendaVisita, Expediente, VerificacionService } from '../../services/verificacion.service';
import { Fiscalizador, Solicitud } from '../../models/solicitud.model';
import { ReniecService } from '../../services/reniec.service';
import { HttpErrorResponse } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { formatTimeDual, validTime24 } from '../../core/time';
import { extractGoogleMapsCoordinates } from '../../core/google-maps-coordinates';

@Component({selector:'app-expediente-nuevo',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./expediente-nuevo.html',styleUrls:['./expedientes.css','./expedientes-extra.css']})
export class ExpedienteNuevoComponent implements OnInit {
  @ViewChild('locationDialog') locationDialog?:ElementRef<HTMLDialogElement>;
  origen='SOLICITUD';detalleOrigen='';dependenciaProcedencia='';referenciaSolicitud='';solicitudCodigo='';objetoFiscalizacion='';observacionesIniciales='';administradoAplica=true;dni='';nombres='';apellidos='';telefono='';direccion='';referencia='';latitud:number|null=null;longitud:number|null=null;ubicacionConfirmada=false;
  programar=false;tipoVisita='PROGRAMADA';fecha='';hora='09:00';fiscalizadorId='';archivos:File[]=[];error='';reniecMensaje='';guardando=false;fiscalizadores:Fiscalizador[]=[];solicitudes:Solicitud[]=[];
  enlaceMaps='';ubicacionMensaje='';coordenadasPropuestas:[number,number]|null=null;agenda:AgendaVisita[]=[];agendaError='';
  readonly origenes=[['SOLICITUD','Solicitud'],['DENUNCIA','Denuncia'],['INICIATIVA_MUNICIPAL','Iniciativa municipal'],['ORDEN_SUPERIOR','Orden superior'],['OPERATIVO_PROGRAMADO','Operativo programado'],['OPERATIVO_INOPINADO','Operativo inopinado'],['OTRO','Otro']];
  constructor(private api:VerificacionService,private reniec:ReniecService,private router:Router,private cdr:ChangeDetectorRef){}
  async ngOnInit(){this.restaurarBorrador();try{const [f,s,e]=await Promise.all([this.api.obtenerFiscalizadores(),this.api.obtenerSolicitudes(),this.api.listarExpedientes()]);this.fiscalizadores=f;const vinculadas=new Set(e.map(x=>x.solicitudCodigo).filter(Boolean));this.solicitudes=s.filter(x=>!vinculadas.has(x.codigo));}catch{this.error='No se pudieron cargar los catálogos municipales.';}this.cargarUbicacionMapa();}
  get origenConDocumento(){return ['DENUNCIA','ORDEN_SUPERIOR','SOLICITUD','OTRO'].includes(this.origen);}
  get nombresCompletos(){return `${this.nombres} ${this.apellidos}`.trim();}
  urlGoogleMaps(){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(this.direccion.trim())}`;}
  abrirModalUbicacion(){this.locationDialog?.nativeElement.showModal();}
  cerrarModalUbicacion(){this.locationDialog?.nativeElement.close();}
  previsualizarEnlaceMaps(){this.coordenadasPropuestas=extractGoogleMapsCoordinates(this.enlaceMaps);
    this.ubicacionMensaje=this.coordenadasPropuestas?'Verifica el punto en Google Maps antes de confirmar.':'El enlace no contiene coordenadas verificables. Usa el selector interno o pega un enlace de Maps con coordenadas.';}
  confirmarCoordenadas(){if(!this.coordenadasPropuestas)return;[this.latitud,this.longitud]=this.coordenadasPropuestas;this.ubicacionConfirmada=true;this.ubicacionMensaje='Ubicación confirmada.';this.cerrarModalUbicacion();}
  async cargarAgenda(){this.agenda=[];this.agendaError='';if(!this.fecha)return;try{this.agenda=await this.api.agendaProgramacion(this.fecha);}catch{this.agendaError='No se pudo consultar la agenda de esta fecha.';}this.cdr.markForCheck();}
  totalFiscalizador(id:string){return this.agenda.filter(v=>v.fiscalizadorId===id&&!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length;}
  conflicto(v:AgendaVisita){return v.fiscalizadorId===this.fiscalizadorId&&v.hora?.slice(0,5)===this.hora&&!['CANCELADA','REPROGRAMADA'].includes(v.estado);}
  horaDual(value:string|null){return formatTimeDual(value);}
  async consultarDni(){if(!/^\d{8}$/.test(this.dni)){this.reniecMensaje='Ingresa un DNI de ocho dígitos.';return;}this.reniecMensaje='Consultando RENIEC…';try{const x=await firstValueFrom(this.reniec.consultarDni(this.dni));this.nombres=x.nombres;this.apellidos=[x.apellidoPaterno,x.apellidoMaterno].filter(Boolean).join(' ');this.reniecMensaje='Datos consultados. Puedes corregirlos manualmente si es necesario.';}catch(e){const s=(e as HttpErrorResponse).status;this.reniecMensaje=s===404?'DNI no encontrado. Completa los datos manualmente.':'RENIEC no está disponible. Completa los datos manualmente.';}this.cdr.markForCheck();}
  cargarUbicacionMapa(){try{const v=localStorage.getItem('sm_temp_ubicacion_mapa');if(v){const p=JSON.parse(v);this.latitud=Number(p.latitud);this.longitud=Number(p.longitud);this.ubicacionConfirmada=Number.isFinite(this.latitud)&&Number.isFinite(this.longitud);localStorage.removeItem('sm_temp_ubicacion_mapa');}}catch{}}
  restaurarBorrador(){try{const raw=sessionStorage.getItem('sm_expediente_nuevo_borrador');if(raw){const d=JSON.parse(raw);Object.assign(this,d);this.tipoVisita='PROGRAMADA';this.archivos=[];this.error='';}}catch{}}
  prepararMapa(){const {origen,detalleOrigen,dependenciaProcedencia,referenciaSolicitud,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,administradoAplica,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,programar,tipoVisita,fecha,hora,fiscalizadorId}=this;sessionStorage.setItem('sm_expediente_nuevo_borrador',JSON.stringify({origen,detalleOrigen,dependenciaProcedencia,referenciaSolicitud,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,administradoAplica,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,programar,tipoVisita,fecha,hora,fiscalizadorId}));}
  async cargarSolicitud(){if(!this.solicitudCodigo)return;try{const s=await this.api.cargarSolicitud(this.solicitudCodigo);this.dni=s.dni;this.nombres=s.nombres;this.apellidos=s.apellidos;this.telefono=s.telefono;this.direccion=s.direccion;this.referencia=s.referencia;this.latitud=s.latitud;this.longitud=s.longitud;this.ubicacionConfirmada=!!s.latitud&&!!s.longitud;}catch{this.error='No se pudo consultar la solicitud seleccionada.';}}
  seleccionarArchivo(ev:Event){const files=Array.from((ev.target as HTMLInputElement).files||[]);if(files.some(f=>!['jpg','jpeg','png','pdf','docx','doc'].includes(f.name.toLowerCase().split('.').pop()||'')||f.size>10*1024*1024)){this.error='Adjunta JPG, PNG, PDF, DOCX o DOC de hasta 10 MB por archivo.';this.archivos=[];return;}this.error='';this.archivos=files;}
  async guardar(){this.error='';if(!this.origen||!this.objetoFiscalizacion.trim()||!this.direccion.trim()||!this.ubicacionConfirmada){this.error='Completa origen, objeto, dirección y ubicación confirmada.';return;}if(this.origen==='SOLICITUD'&&(!this.dependenciaProcedencia.trim()||!this.referenciaSolicitud.trim())){this.error='Indica la dependencia y la referencia de la solicitud recibida.';return;}if(this.administradoAplica&&(!/^\d{8}$/.test(this.dni)||!this.nombres.trim()||!this.apellidos.trim())){this.error='Completa DNI, nombres y apellidos del administrado.';return;}if(this.programar&&(!this.fecha||!validTime24(this.hora)||!this.fiscalizadorId)){this.error='Para programar, indica fecha, hora válida HH:mm y fiscalizador.';return;}this.guardando=true;try{const expediente={origen:this.origen,detalleOrigen:this.detalleOrigen||null,solicitudCodigo:this.origen==='SOLICITUD'?this.solicitudCodigo||null:null,objetoFiscalizacion:this.objetoFiscalizacion.trim(),observacionesIniciales:this.observacionesIniciales||null,tipoAdministrado:this.administradoAplica?'PERSONA_NATURAL':null,documentoAdministrado:this.administradoAplica?this.dni:null,nombreAdministrado:this.administradoAplica?this.nombres.trim():null,administradoApellidos:this.administradoAplica?this.apellidos.trim():null,telefonoContacto:this.administradoAplica?this.telefono||null:null,direccionFiscalizada:this.direccion.trim(),referenciaDomicilio:this.referencia||null,latitud:this.latitud,longitud:this.longitud};const e:Expediente=await this.api.crearFiscalizacion({expediente,dependenciaProcedencia:this.dependenciaProcedencia||null,referenciaSolicitud:this.referenciaSolicitud||null,primeraProgramacion:this.programar?{fecha:this.fecha,hora:this.hora,fiscalizadorId:this.fiscalizadorId,tipoVisita:this.tipoVisita}:null},this.archivos);sessionStorage.removeItem('sm_expediente_nuevo_borrador');await this.router.navigate(['/expedientes',e.codigo]);}catch(e){const status=(e as HttpErrorResponse).status;this.error=status===403?'Tu usuario no tiene permiso para completar esta acción.':(e as HttpErrorResponse).error?.message||'No se pudo crear la fiscalización. Revisa fecha, disponibilidad y documentos.';}finally{this.guardando=false;this.cdr.markForCheck();}}
}
