import { AfterViewInit, ChangeDetectorRef, Component, ElementRef, NgZone, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AgendaVisita, Expediente, VerificacionService } from '../../services/verificacion.service';
import { Fiscalizador, Solicitud } from '../../models/solicitud.model';
import { ReniecService } from '../../services/reniec.service';
import { HttpErrorResponse } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { formatTimeDual, validTime24 } from '../../core/time';
import * as L from 'leaflet';
import {UsuariosService,UserPreferences} from '../../services/usuarios.service';
import {extractGoogleMapsCoordinates} from '../../core/google-maps-coordinates';

@Component({selector:'app-expediente-nuevo',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./expediente-nuevo.html',styleUrls:['./expedientes.css','./expedientes-extra.css']})
export class ExpedienteNuevoComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('locationPreview') set locationPreview(element:ElementRef<HTMLDivElement>|undefined){if(element&&(!this.mapaPreview||this.mapaPreview.getContainer()!==element.nativeElement))setTimeout(()=>{this.mapaPreview?.remove();this.mapaPreview=undefined;this.inicializarMapaPreview(element.nativeElement);});}
  private mapaPreview?:L.Map;private marcadorPreview?:L.Marker;private iconoPreview?:L.DivIcon;private timerDireccion?:number;private busquedaAbort?:AbortController;private dniTimer?:number;private ultimoDni='';
  origen='SOLICITUD';detalleOrigen='';dependenciaProcedencia='';referenciaSolicitud='';solicitudCodigo='';objetoFiscalizacion='';observacionesIniciales='';administradoAplica=true;dni='';nombres='';apellidos='';telefono='';direccion='';referencia='';latitud:number|null=null;longitud:number|null=null;ubicacionConfirmada=false;
  programar=false;tipoVisita='PROGRAMADA';fecha='';hora='09:00';fiscalizadorId='';archivos:File[]=[];error='';reniecMensaje='';guardando=false;fiscalizadores:Fiscalizador[]=[];solicitudes:Solicitud[]=[];
  sobrecargaConfirmada=false;agenda:AgendaVisita[]=[];agendaError='';autoUbicacionBuscando=false;autoUbicacionMensaje='';
  preferencias:UserPreferences={mapaInterno:false,googleExterno:false,googleUrl:false,descargarJornadaHtml:false};googleModal=false;metodoUbicacion='';googleLink='';googleError='';dniDisponible=false;limiteDiario=5;
  readonly origenes=[['SOLICITUD','Solicitud'],['DENUNCIA','Denuncia'],['INICIATIVA_MUNICIPAL','Iniciativa municipal'],['ORDEN_SUPERIOR','Orden superior'],['OPERATIVO_PROGRAMADO','Operativo programado'],['OPERATIVO_INOPINADO','Operativo inopinado'],['OTRO','Otro']];
  constructor(private api:VerificacionService,private reniec:ReniecService,private users:UsuariosService,private router:Router,private zone:NgZone,private cdr:ChangeDetectorRef){}
  async ngOnInit(){this.restaurarBorrador();try{const [f,s,e]=await Promise.all([this.api.obtenerFiscalizadores(),this.api.obtenerSolicitudes(),this.api.listarExpedientes()]);this.fiscalizadores=f;const vinculadas=new Set(e.map(x=>x.solicitudCodigo).filter(Boolean));this.solicitudes=s.filter(x=>!vinculadas.has(x.codigo));}catch{this.error='No se pudieron cargar los catálogos municipales.';}const [preferences,limit,identity]=await Promise.allSettled([this.users.misPreferencias(),this.users.limiteDiario(),this.users.identidadDisponible()]);if(preferences.status==='fulfilled')this.preferencias=preferences.value;else this.error='No se pudieron cargar los métodos de ubicación de tu cuenta.';if(limit.status==='fulfilled')this.limiteDiario=limit.value;if(identity.status==='fulfilled')this.dniDisponible=identity.value;this.cargarUbicacionMapa();this.cdr.markForCheck();}
  ngAfterViewInit(){}
  ngOnDestroy(){if(this.timerDireccion)window.clearTimeout(this.timerDireccion);if(this.dniTimer)window.clearTimeout(this.dniTimer);this.busquedaAbort?.abort();this.mapaPreview?.remove();}
  get origenConDocumento(){return ['DENUNCIA','ORDEN_SUPERIOR','SOLICITUD','OTRO'].includes(this.origen);}
  get nombresCompletos(){return `${this.nombres} ${this.apellidos}`.trim();}
  seleccionarUbicacion(){if(!this.preferencias.mapaInterno)return;this.prepararMapa();this.router.navigate(['/mapa'],{queryParams:{retorno:'expedientes/nuevo',q:this.direccion.trim()||null}});}
  abrirGoogle(){if(!this.preferencias.googleExterno)return;const query=encodeURIComponent([this.direccion,this.referencia,'San Miguel, Puno, Perú'].filter(Boolean).join(', '));window.open(`https://www.google.com/maps/search/?api=1&query=${query}`,'_blank','noopener');this.googleModal=true;this.googleError='';}
  async leerPortapapeles(){try{this.googleLink=await navigator.clipboard.readText();}catch{this.googleError='El navegador no permitió leer el portapapeles. Pega el enlace manualmente.';}}
  async confirmarGoogle(){this.googleError='';const method=this.googleModal?'GOOGLE_EXTERNO':'GOOGLE_URL';let url=this.googleLink.trim();let point=extractGoogleMapsCoordinates(url);if(!point){try{url=await this.api.resolverGoogleMaps(url);point=extractGoogleMapsCoordinates(url);}catch{}}
    if(!point){this.googleError='El enlace no contiene un punto del predio verificable. En Google Maps usa Compartir sobre un marcador, no el centro del mapa.';return;}
    [this.latitud,this.longitud]=point;this.googleLink=url;this.metodoUbicacion=method;this.ubicacionConfirmada=true;this.googleModal=false;this.autoUbicacionMensaje='Punto confirmado desde el enlace compartido.';this.cdr.detectChanges();this.marcarVistaPrevia(point[0],point[1]);}
  ajustarUbicacion(){this.ubicacionConfirmada=false;this.metodoUbicacion='';this.googleError='';this.cdr.markForCheck();}
  dniActualizado(){if(this.dniTimer)window.clearTimeout(this.dniTimer);if(!this.dniDisponible||!/^\d{8}$/.test(this.dni)||this.dni===this.ultimoDni)return;this.dniTimer=window.setTimeout(()=>void this.consultarDni(),450);}
  direccionActualizada(valor:string){if(this.timerDireccion)window.clearTimeout(this.timerDireccion);this.busquedaAbort?.abort();this.ubicacionConfirmada=false;this.latitud=null;this.longitud=null;this.autoUbicacionMensaje='';this.quitarMarcadorPreview();const direccion=valor.trim();if(direccion.length<6){this.autoUbicacionBuscando=false;this.autoUbicacionMensaje=direccion?'Completa el jirón y número para ubicar la casa.':'';return;}this.autoUbicacionBuscando=true;this.autoUbicacionMensaje='Buscando la dirección en el mapa…';this.timerDireccion=window.setTimeout(()=>void this.buscarDireccionAutomatica(direccion),900);}
  private inicializarMapaPreview(host:HTMLDivElement){this.iconoPreview=L.divIcon({className:'location-preview-pin',html:'<svg xmlns="http://www.w3.org/2000/svg" width="36" height="44" viewBox="0 0 36 44" aria-hidden="true"><path fill="#dc2626" stroke="#fff" stroke-width="2" d="M18 2C9.2 2 2 9.2 2 18c0 10.4 16 24 16 24s16-13.6 16-24C34 9.2 26.8 2 18 2Z"/><circle cx="18" cy="18" r="5" fill="#fff"/></svg>',iconSize:[36,44],iconAnchor:[18,43],popupAnchor:[0,-39]});const lat=this.latitud??-15.3977773,lng=this.longitud??-70.1217652;this.mapaPreview=L.map(host,{scrollWheelZoom:false}).setView([lat,lng],this.latitud!==null?17:14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(this.mapaPreview);if(this.ubicacionConfirmada&&this.latitud!==null&&this.longitud!==null)this.marcarVistaPrevia(this.latitud,this.longitud);}
  private marcarVistaPrevia(lat:number,lng:number){if(!this.mapaPreview||!this.iconoPreview)return;if(this.marcadorPreview)this.mapaPreview.removeLayer(this.marcadorPreview);const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=this.nombresCompletos||'Ubicación del predio';const address=document.createElement('div');address.textContent=this.direccion||'Dirección del predio';popup.append(title,address);if(this.telefono){const phone=document.createElement('div');phone.textContent=`Teléfono: ${this.telefono}`;popup.append(phone);}this.marcadorPreview=L.marker([lat,lng],{icon:this.iconoPreview}).addTo(this.mapaPreview).bindPopup(popup).openPopup();this.mapaPreview.setView([lat,lng],17);}
  actualizarPopupPreview(){if(!this.marcadorPreview)return;const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=this.nombresCompletos||'Ubicación del predio';const address=document.createElement('div');address.textContent=this.direccion||'Dirección del predio';popup.append(title,address);if(this.telefono){const phone=document.createElement('div');phone.textContent=`Teléfono: ${this.telefono}`;popup.append(phone);}this.marcadorPreview.setPopupContent(popup);}
  private quitarMarcadorPreview(){if(this.mapaPreview&&this.marcadorPreview){this.mapaPreview.removeLayer(this.marcadorPreview);this.marcadorPreview=undefined;}}
  private async buscarDireccionAutomatica(direccion:string){const controller=new AbortController();this.busquedaAbort=controller;const timeout=window.setTimeout(()=>controller.abort(),10000);try{const query=`${direccion}, San Miguel, San Román, Puno, Perú`;const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&countrycodes=pe&q=${encodeURIComponent(query)}`,{headers:{'Accept-Language':'es'},signal:controller.signal});if(!response.ok)throw new Error('geocoding');const resultados=await response.json() as Array<{display_name:string;lat:string;lon:string;addresstype?:string;type?:string}>;this.zone.run(()=>{if(this.direccion.trim()!==direccion)return;const punto=resultados.find(x=>/san miguel/i.test(x.display_name))||resultados[0];if(punto){const lat=Number(punto.lat),lng=Number(punto.lon);if(Number.isFinite(lat)&&Number.isFinite(lng)){this.latitud=lat;this.longitud=lng;const exacta=['house','building'].includes((punto.addresstype||punto.type||'').toLowerCase());this.ubicacionConfirmada=false;this.autoUbicacionMensaje=exacta?'Dirección encontrada. Confirma el punto exacto con un método habilitado.':'Dirección aproximada. Confirma el punto exacto con un método habilitado.';}else this.autoUbicacionMensaje='No pude interpretar las coordenadas. Selecciona el punto en el mapa.';}else this.autoUbicacionMensaje='No encontré esa dirección. Puedes ubicarla manualmente en el mapa.';this.autoUbicacionBuscando=false;this.cdr.markForCheck();});}catch{this.zone.run(()=>{if(this.direccion.trim()!==direccion)return;this.autoUbicacionMensaje='No se pudo buscar automáticamente. Usa el mapa para marcar la casa.';this.autoUbicacionBuscando=false;this.cdr.markForCheck();});}finally{window.clearTimeout(timeout);}}
  async cargarAgenda(){this.sobrecargaConfirmada=false;this.agenda=[];this.agendaError='';if(!this.fecha)return;try{this.agenda=await this.api.agendaProgramacion(this.fecha);}catch{this.agendaError='No se pudo consultar la agenda de esta fecha.';}this.cdr.markForCheck();}
  get cargaValida(){return this.agenda.filter(v=>!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length;}
  totalFiscalizador(id:string){return this.agenda.filter(v=>v.fiscalizadorId===id&&!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length;}
  conflicto(v:AgendaVisita){return v.fiscalizadorId===this.fiscalizadorId&&v.hora?.slice(0,5)===this.hora&&!['CANCELADA','REPROGRAMADA'].includes(v.estado);}
  horaDual(value:string|null){return formatTimeDual(value);}
  async consultarDni(){if(!this.dniDisponible||!/^\d{8}$/.test(this.dni)||this.dni===this.ultimoDni)return;const queried=this.dni;this.ultimoDni=queried;this.reniecMensaje='Consultando DNI…';try{const x=await firstValueFrom(this.reniec.consultarDni(queried));if(this.dni===queried){if(!this.nombres.trim())this.nombres=x.nombres;if(!this.apellidos.trim())this.apellidos=[x.apellidoPaterno,x.apellidoMaterno].filter(Boolean).join(' ');this.reniecMensaje='Datos sugeridos; puedes corregirlos manualmente.';}}catch(e){const status=(e as HttpErrorResponse).status;this.reniecMensaje=status===404?'DNI no encontrado. Completa los datos manualmente.':'Servicio DNI no disponible. Completa los datos manualmente.';}this.cdr.markForCheck();}
  cargarUbicacionMapa(){try{const v=localStorage.getItem('sm_temp_ubicacion_mapa');if(v){const p=JSON.parse(v);this.latitud=Number(p.latitud);this.longitud=Number(p.longitud);this.ubicacionConfirmada=Number.isFinite(this.latitud)&&Number.isFinite(this.longitud);this.metodoUbicacion='MAPA_INTERNO';this.autoUbicacionMensaje='Punto confirmado en el mapa.';localStorage.removeItem('sm_temp_ubicacion_mapa');if(this.latitud!==null&&this.longitud!==null)this.marcarVistaPrevia(this.latitud,this.longitud);}}catch{}}
  restaurarBorrador(){try{const raw=sessionStorage.getItem('sm_expediente_nuevo_borrador');if(raw){const d=JSON.parse(raw);Object.assign(this,d);this.tipoVisita='PROGRAMADA';this.archivos=[];this.error='';}}catch{}}
  prepararMapa(){const {origen,detalleOrigen,dependenciaProcedencia,referenciaSolicitud,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,administradoAplica,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,metodoUbicacion,googleLink,programar,tipoVisita,fecha,hora,fiscalizadorId}=this;sessionStorage.setItem('sm_expediente_nuevo_borrador',JSON.stringify({origen,detalleOrigen,dependenciaProcedencia,referenciaSolicitud,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,administradoAplica,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,metodoUbicacion,googleLink,programar,tipoVisita,fecha,hora,fiscalizadorId}));}
  async cargarSolicitud(){if(!this.solicitudCodigo)return;try{const s=await this.api.cargarSolicitud(this.solicitudCodigo);this.dni=s.dni;this.nombres=s.nombres;this.apellidos=s.apellidos;this.telefono=s.telefono;this.direccion=s.direccion;this.referencia=s.referencia;this.latitud=s.latitud;this.longitud=s.longitud;this.ubicacionConfirmada=!!s.latitud&&!!s.longitud;this.metodoUbicacion='SOLICITUD_EXISTENTE';this.autoUbicacionMensaje=this.ubicacionConfirmada?'Ubicación guardada para esta solicitud.':'';if(this.latitud!==null&&this.longitud!==null)this.marcarVistaPrevia(this.latitud,this.longitud);}catch{this.error='No se pudo consultar la solicitud seleccionada.';}}
  seleccionarArchivo(ev:Event){const files=Array.from((ev.target as HTMLInputElement).files||[]);if(files.some(f=>!['jpg','jpeg','png','pdf','docx','doc'].includes(f.name.toLowerCase().split('.').pop()||'')||f.size>10*1024*1024)){this.error='Adjunta JPG, PNG, PDF, DOCX o DOC de hasta 10 MB por archivo.';this.archivos=[];return;}this.error='';this.archivos=files;}
  async guardar(){this.error='';const ubicacionValida=this.ubicacionConfirmada&&this.latitud!==null&&this.longitud!==null&&Number.isFinite(this.latitud)&&Number.isFinite(this.longitud);if(!this.origen||!this.objetoFiscalizacion.trim()||!this.direccion.trim()||!ubicacionValida){this.error='Completa origen, objeto y dirección, y confirma la ubicación del predio.';return;}if(this.origen==='SOLICITUD'&&(!this.dependenciaProcedencia.trim()||!this.referenciaSolicitud.trim())){this.error='Indica la dependencia y la referencia de la solicitud recibida.';return;}if(this.administradoAplica&&(!/^\d{8}$/.test(this.dni)||!this.nombres.trim()||!this.apellidos.trim())){this.error='Completa DNI, nombres y apellidos del administrado.';return;}if(this.programar&&(!this.fecha||!validTime24(this.hora)||!this.fiscalizadorId)){this.error='Para programar, indica fecha, hora válida HH:mm y fiscalizador.';return;}if(this.programar&&this.cargaValida+1>this.limiteDiario&&!this.sobrecargaConfirmada){this.sobrecargaConfirmada=true;this.error='La programación superará el límite orientativo de '+this.limiteDiario+' visitas. Pulsa de nuevo Crear fiscalización para continuar.';return;}this.guardando=true;try{const expediente={origen:this.origen,detalleOrigen:this.detalleOrigen||null,solicitudCodigo:this.origen==='SOLICITUD'?this.solicitudCodigo||null:null,objetoFiscalizacion:this.objetoFiscalizacion.trim(),observacionesIniciales:this.observacionesIniciales||null,tipoAdministrado:this.administradoAplica?'PERSONA_NATURAL':null,documentoAdministrado:this.administradoAplica?this.dni:null,nombreAdministrado:this.administradoAplica?this.nombres.trim():null,administradoApellidos:this.administradoAplica?this.apellidos.trim():null,telefonoContacto:this.administradoAplica?this.telefono||null:null,direccionFiscalizada:this.direccion.trim(),referenciaDomicilio:this.referencia||null,latitud:this.latitud,longitud:this.longitud};const e:Expediente=await this.api.crearFiscalizacion({expediente,dependenciaProcedencia:this.dependenciaProcedencia||null,referenciaSolicitud:this.referenciaSolicitud||null,metodoUbicacion:this.metodoUbicacion,enlaceGoogle:this.metodoUbicacion.startsWith('GOOGLE')?this.googleLink:null,primeraProgramacion:this.programar?{fecha:this.fecha,hora:this.hora,fiscalizadorId:this.fiscalizadorId,tipoVisita:this.tipoVisita}:null},this.archivos);sessionStorage.removeItem('sm_expediente_nuevo_borrador');await this.router.navigate(['/expedientes',e.codigo]);}catch(e){const status=(e as HttpErrorResponse).status;this.error=status===403?'Tu usuario no tiene permiso para completar esta acción.':(e as HttpErrorResponse).error?.message||'No se pudo crear la fiscalización. Revisa fecha, disponibilidad y documentos.';}finally{this.guardando=false;this.cdr.markForCheck();}}
}
