import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ActaFiscalizacion, AgendaVisita, Expediente, ExpedienteDocumento, ProgramacionExpediente, VerificacionService } from '../../services/verificacion.service';
import { Fiscalizador } from '../../models/solicitud.model';
import { formatTimeDual, validTime24 } from '../../core/time';
import { formatLimaLocalDateTime } from '../../core/date';
import { UsuariosService } from '../../services/usuarios.service';

@Component({selector:'app-expediente-detalle',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./expediente-detalle.html',styleUrls:['./expedientes.css','./expediente-detalle.css']})
export class ExpedienteDetalleComponent implements OnInit {
  expediente:Expediente|null=null; documentos:ExpedienteDocumento[]=[]; actas:ActaFiscalizacion[]=[]; ciclos:any[]=[]; fiscalizadores:Fiscalizador[]=[]; cargando=true; error=''; accion:''|'programar'|'reprogramar'|'cancelar'=''; programacion:ProgramacionExpediente|null=null;
  fecha='';hora='09:00';fiscalizadorId='';tipoVisita='PROGRAMADA';motivo='';
  private users=inject(UsuariosService);limiteDiario=5;sobrecargaConfirmada=false;agenda:AgendaVisita[]=[];agendaError='';archivos:File[]=[];adjuntando=false;
  constructor(private route:ActivatedRoute,private router:Router,private api:VerificacionService,private cdr:ChangeDetectorRef){}
  async ngOnInit(){this.limiteDiario=await this.users.limiteDiario().catch(()=>5);await this.cargar();try{this.fiscalizadores=await this.api.obtenerFiscalizadores();}catch{}}
  async cargar(){this.cargando=true;try{this.expediente=await this.api.obtenerExpediente(this.route.snapshot.paramMap.get('codigo')||'');const [actas,ciclos,documentos]=await Promise.all([this.api.actasExpediente(this.expediente.codigo),this.api.ciclosFiscalizacion(this.expediente.codigo),this.api.documentosExpediente(this.expediente.codigo)]);this.actas=actas;this.ciclos=ciclos.ciclos||[];this.documentos=documentos;}catch{this.error='No se pudo cargar el expediente, actas o documentos.';}finally{this.cargando=false;this.cdr.markForCheck();}}
  origen(o:string){return ({SOLICITUD:'Solicitud',DENUNCIA:'Denuncia',INICIATIVA_MUNICIPAL:'Iniciativa municipal',ORDEN_SUPERIOR:'Orden superior',OPERATIVO_PROGRAMADO:'Operativo programado',OPERATIVO_INOPINADO:'Operativo inopinado',OTRO:'Otro'} as Record<string,string>)[o]||o;}
  horaDual(value:string|null){return formatTimeDual(value);}
  fechaLima(value:string|null|undefined){return formatLimaLocalDateTime(value);}
  tipoArchivo(nombre:string,mime:string){const ext=nombre.toLowerCase().split('.').pop()||'';return ['pdf','doc','docx','jpg','jpeg','png'].includes(ext)?ext.toUpperCase():mime;}
  async cargarAgenda(){this.sobrecargaConfirmada=false;this.agenda=[];this.agendaError='';if(!this.fecha)return;try{this.agenda=await this.api.agendaProgramacion(this.fecha);}catch{this.agendaError='No se pudo consultar la agenda.';}this.cdr.markForCheck();}
  get cargaValida(){return this.agenda.filter(v=>!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length;}
  totalFiscalizador(id:string){return this.agenda.filter(v=>v.fiscalizadorId===id&&!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length;}
  conflicto(v:AgendaVisita){return v.fiscalizadorId===this.fiscalizadorId&&v.hora?.slice(0,5)===this.hora&&!['CANCELADA','REPROGRAMADA'].includes(v.estado);}
  seleccionarDocumentos(event:Event){this.archivos=Array.from((event.target as HTMLInputElement).files||[]);this.error='';if(this.archivos.some(f=>!['jpg','jpeg','png','pdf','doc','docx'].includes(f.name.toLowerCase().split('.').pop()||'')||f.size>10*1024*1024)){this.archivos=[];this.error='Adjunta PDF, DOC, DOCX, JPG o PNG de hasta 10 MB por archivo.';}}
  async adjuntarDocumentos(){if(!this.expediente||!this.archivos.length)return;this.adjuntando=true;this.error='';try{this.documentos=await this.api.adjuntarDocumentosExpediente(this.expediente.codigo,this.archivos);this.archivos=[];}catch{this.error='No se pudieron adjuntar los documentos. Revisa tipos, tamaño y permisos.';}finally{this.adjuntando=false;this.cdr.markForCheck();}}
  vigente(){return this.expediente?[...this.expediente.programaciones].reverse().find(p=>p.estado!=='REPROGRAMADA')??null:null;}
  abrir(a:'reprogramar'|'cancelar',p:ProgramacionExpediente){this.sobrecargaConfirmada=false;this.accion=a;this.programacion=p;this.fecha='';this.hora=p.hora||'09:00';this.fiscalizadorId=p.fiscalizadorId||'';this.tipoVisita=p.tipoVisita;this.motivo='';this.error='';}
  abrirProgramacion(){this.sobrecargaConfirmada=false;this.accion='programar';this.programacion=null;this.fecha='';this.hora='09:00';this.fiscalizadorId='';this.tipoVisita='PROGRAMADA';this.error='';}
  cerrar(){this.accion='';this.programacion=null;}
  puedeModificar(p:ProgramacionExpediente){return this.expediente?.estado!=='CERRADO'&&['PROGRAMADA','VENCIDA'].includes(p.estado);}
  async revisar(d:any){try{const r=await this.api.iniciarRevision(d.diligenciaId);await this.router.navigate(['/revisiones',r.revision.id]);}catch{this.error='No se pudo abrir la revisión de esta diligencia.';}this.cdr.markForCheck();}
  async guardar(){if(this.accion!=='programar'&&(!this.programacion||!this.motivo.trim())){this.error='El motivo es obligatorio.';return;}if(this.accion!=='cancelar'&&(!this.fecha||!validTime24(this.hora)||!this.fiscalizadorId)){this.error='Indica fecha, hora HH:mm y fiscalizador.';return;}if(this.accion!=='cancelar'){if(!this.agenda.length)await this.cargarAgenda();const count=this.agenda.filter(v=>!['CANCELADA','REPROGRAMADA'].includes(v.estado)).length+(this.accion==='reprogramar'&&this.programacion?.fecha===this.fecha?0:1);if(count>this.limiteDiario&&!this.sobrecargaConfirmada){this.sobrecargaConfirmada=true;this.error='La agenda superará el límite orientativo de '+this.limiteDiario+' visitas. Pulsa Guardar otra vez para continuar.';return;}}try{if(this.accion==='programar'&&this.expediente){await this.api.programarExpediente(this.expediente.codigo,{fecha:this.fecha,hora:this.hora,fiscalizadorId:this.fiscalizadorId,tipoVisita:this.tipoVisita});}else if(this.accion==='reprogramar'&&this.programacion){await this.api.reprogramar(this.programacion.id,{fecha:this.fecha,hora:this.hora,motivo:this.motivo,fiscalizadorId:this.fiscalizadorId,tipoVisita:this.tipoVisita});}else if(this.accion==='cancelar'&&this.programacion){await this.api.cancelarProgramacion(this.programacion.id,this.motivo);}this.cerrar();await this.cargar();}catch{this.error='No se pudo completar la operación. Verifica fecha, disponibilidad y permisos.';}this.cdr.markForCheck();}
  async descargarDocumento(d:ExpedienteDocumento){if(!this.expediente)return;const viewer=d.tipoMime==='application/pdf'?window.open('about:blank','_blank'):null;if(viewer)viewer.opener=null;try{const blob=await this.api.descargarDocumentoExpediente(this.expediente.codigo,d.id);if(d.tipoMime==='application/pdf'){const url=URL.createObjectURL(new Blob([blob],{type:'application/pdf'}));if(viewer)viewer.location.href=url;else this.error='El navegador bloqueó la pestaña del PDF. Permite ventanas emergentes e inténtalo de nuevo.';setTimeout(()=>URL.revokeObjectURL(url),60000);}else this.abrirBlob(blob,d.nombre);}catch{viewer?.close();this.error='No se pudo abrir el documento.';}}
  async documento(){if(!this.expediente)return;const viewer=window.open('about:blank','_blank');if(viewer)viewer.opener=null;try{const blob=await this.api.abrirSustento(this.expediente.codigo);const url=URL.createObjectURL(new Blob([blob],{type:'application/pdf'}));if(viewer)viewer.location.href=url;else this.error='El navegador bloqueó la pestaña del PDF.';setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{viewer?.close();this.error='No se pudo abrir el documento de sustento.';}}
  async reporte(){if(!this.expediente?.solicitudCodigo)return;try{const blob=await this.api.abrirReporte(this.expediente.solicitudCodigo);window.open(URL.createObjectURL(blob),'_blank','noopener');}catch{this.error='No se pudo abrir el reporte del fiscalizador.';}}
  async descargarActa(acta:ActaFiscalizacion){try{const blob=await this.api.descargarActa(acta.id);this.abrirBlob(blob,acta.pdfGeneradoNombre);}catch{this.error='No se pudo descargar el acta generada.';}}
  async descargarCopiaFirmada(acta:ActaFiscalizacion){try{const blob=await this.api.descargarCopiaFirmadaActa(acta.id);this.abrirBlob(blob,acta.pdfFirmadoNombre||'Acta-firmada.pdf');}catch{this.error='No se pudo descargar la copia firmada.';}}
  private abrirBlob(blob:Blob,nombre:string|null){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=nombre||'Acta.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  nombreEvento(code:string){return ({EXPEDIENTE_CREADO:'Expediente creado',EXPEDIENTE_EDITADO:'Expediente actualizado',PROGRAMACION_CREADA:'Visita programada',PROGRAMACION_REPROGRAMADA:'Visita reprogramada',PROGRAMACION_CREADA_POR_REPROGRAMACION:'Nueva fecha programada',PROGRAMACION_CANCELADA:'Visita cancelada',PROGRAMACION_VENCIDA:'Visita vencida',DILIGENCIA_INICIADA:'Diligencia iniciada',DILIGENCIA_FINALIZADA:'Diligencia finalizada'} as Record<string,string>)[code]||code.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());}
  detalles(v:string|null):string[]{if(!v)return[];try{const value=JSON.parse(v);if(value&&typeof value==='object'&&!Array.isArray(value))return Object.entries(value).map(([k,x])=>`${k.replace(/([A-Z])/g,' $1').replaceAll('_',' ')}: ${x===null?'—':typeof x==='object'?'Detalle compuesto conservado en auditoría':x}`);return [String(value)];}catch{return /^[\[{]/.test(v.trim())?['Detalle técnico conservado en el historial; no disponible en esta vista.']: [v];}}
}
