import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { Expediente, VerificacionService } from '../../services/verificacion.service';
import { Fiscalizador, Solicitud } from '../../models/solicitud.model';
import { ReniecService } from '../../services/reniec.service';
import { HttpErrorResponse } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

@Component({selector:'app-expediente-nuevo',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./expediente-nuevo.html',styleUrls:['./expedientes.css','./expedientes-extra.css']})
export class ExpedienteNuevoComponent implements OnInit {
  origen='INICIATIVA_MUNICIPAL';detalleOrigen='';solicitudCodigo='';objetoFiscalizacion='';observacionesIniciales='';dni='';nombres='';apellidos='';telefono='';direccion='';referencia='';latitud:number|null=null;longitud:number|null=null;ubicacionConfirmada=false;
  programar=false;tipoVisita='PROGRAMADA';fecha='';hora='09:00';fiscalizadorId='';archivo:File|null=null;error='';reniecMensaje='';guardando=false;fiscalizadores:Fiscalizador[]=[];solicitudes:Solicitud[]=[];
  readonly origenes=[['SOLICITUD','Solicitud'],['DENUNCIA','Denuncia'],['INICIATIVA_MUNICIPAL','Iniciativa municipal'],['ORDEN_SUPERIOR','Orden superior'],['OPERATIVO_PROGRAMADO','Operativo programado'],['OPERATIVO_INOPINADO','Operativo inopinado'],['OTRO','Otro']];
  constructor(private api:VerificacionService,private reniec:ReniecService,private router:Router,private cdr:ChangeDetectorRef){}
  async ngOnInit(){this.restaurarBorrador();try{const [f,s,e]=await Promise.all([this.api.obtenerFiscalizadores(),this.api.obtenerSolicitudes(),this.api.listarExpedientes()]);this.fiscalizadores=f;const vinculadas=new Set(e.map(x=>x.solicitudCodigo).filter(Boolean));this.solicitudes=s.filter(x=>!vinculadas.has(x.codigo));}catch{this.error='No se pudieron cargar los catálogos municipales.';}this.cargarUbicacionMapa();}
  get origenConDocumento(){return ['DENUNCIA','ORDEN_SUPERIOR','SOLICITUD','OTRO'].includes(this.origen);}
  get nombresCompletos(){return `${this.nombres} ${this.apellidos}`.trim();}
  urlGoogleMaps(){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(this.direccion.trim())}`;}
  async consultarDni(){if(!/^\d{8}$/.test(this.dni)){this.reniecMensaje='Ingresa un DNI de ocho dígitos.';return;}this.reniecMensaje='Consultando RENIEC…';try{const x=await firstValueFrom(this.reniec.consultarDni(this.dni));this.nombres=x.nombres;this.apellidos=[x.apellidoPaterno,x.apellidoMaterno].filter(Boolean).join(' ');this.reniecMensaje='Datos consultados. Puedes corregirlos manualmente si es necesario.';}catch(e){const s=(e as HttpErrorResponse).status;this.reniecMensaje=s===404?'DNI no encontrado. Completa los datos manualmente.':'RENIEC no está disponible. Completa los datos manualmente.';}this.cdr.markForCheck();}
  cargarUbicacionMapa(){try{const v=localStorage.getItem('sm_temp_ubicacion_mapa');if(v){const p=JSON.parse(v);this.latitud=Number(p.latitud);this.longitud=Number(p.longitud);this.ubicacionConfirmada=Number.isFinite(this.latitud)&&Number.isFinite(this.longitud);localStorage.removeItem('sm_temp_ubicacion_mapa');}}catch{}}
  restaurarBorrador(){try{const raw=sessionStorage.getItem('sm_expediente_nuevo_borrador');if(raw){const d=JSON.parse(raw);Object.assign(this,d);this.archivo=null;this.error='';}}catch{}}
  prepararMapa(){const {origen,detalleOrigen,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,programar,tipoVisita,fecha,hora,fiscalizadorId}=this;sessionStorage.setItem('sm_expediente_nuevo_borrador',JSON.stringify({origen,detalleOrigen,solicitudCodigo,objetoFiscalizacion,observacionesIniciales,dni,nombres,apellidos,telefono,direccion,referencia,latitud,longitud,ubicacionConfirmada,programar,tipoVisita,fecha,hora,fiscalizadorId}));}
  async cargarSolicitud(){if(!this.solicitudCodigo)return;try{const s=await this.api.cargarSolicitud(this.solicitudCodigo);this.dni=s.dni;this.nombres=s.nombres;this.apellidos=s.apellidos;this.telefono=s.telefono;this.direccion=s.direccion;this.referencia=s.referencia;this.latitud=s.latitud;this.longitud=s.longitud;this.ubicacionConfirmada=!!s.latitud&&!!s.longitud;}catch{this.error='No se pudo consultar la solicitud seleccionada.';}}
  seleccionarArchivo(ev:Event){const f=(ev.target as HTMLInputElement).files?.[0]||null;if(f&&(!f.name.toLowerCase().endsWith('.pdf')||(!!f.type&&f.type!=='application/pdf'))){this.error='Adjunta un archivo PDF válido.';this.archivo=null;return;}this.error='';this.archivo=f;}
  async guardar(){this.error='';if(!this.origen||!this.objetoFiscalizacion.trim()||!/^\d{8}$/.test(this.dni)||!this.nombres.trim()||!this.apellidos.trim()||!this.direccion.trim()||!this.ubicacionConfirmada){this.error='Completa origen, objeto, datos del administrado, dirección y ubicación confirmada.';return;}if(this.programar&&(!this.fecha||!this.hora||!this.fiscalizadorId)){this.error='Para programar, indica fecha, hora y fiscalizador.';return;}this.guardando=true;try{let e:Expediente=await this.api.crearExpediente({origen:this.origen,detalleOrigen:this.detalleOrigen||null,solicitudCodigo:this.origen==='SOLICITUD'?this.solicitudCodigo||null:null,objetoFiscalizacion:this.objetoFiscalizacion.trim(),observacionesIniciales:this.observacionesIniciales||null,tipoAdministrado:'PERSONA_NATURAL',documentoAdministrado:this.dni,nombreAdministrado:this.nombres.trim(),administradoApellidos:this.apellidos.trim(),telefonoContacto:this.telefono||null,direccionFiscalizada:this.direccion.trim(),referenciaDomicilio:this.referencia||null,latitud:this.latitud,longitud:this.longitud});if(this.archivo)e=await this.api.adjuntarSustento(e.codigo,this.archivo);if(this.programar)await this.api.programarExpediente(e.codigo,{fecha:this.fecha,hora:this.hora,fiscalizadorId:this.fiscalizadorId,tipoVisita:this.tipoVisita});sessionStorage.removeItem('sm_expediente_nuevo_borrador');await this.router.navigate(['/expedientes',e.codigo]);}catch(e){const status=(e as HttpErrorResponse).status;this.error=status===403?'Tu usuario no tiene permiso para completar esta acción.':(e as HttpErrorResponse).error?.message||'No se pudo crear el expediente. Revisa la fecha, disponibilidad del fiscalizador y los datos.';}finally{this.guardando=false;this.cdr.markForCheck();}}
}
