import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { firstValueFrom, Observable } from 'rxjs';
import { EstadoSolicitud, Solicitud, Fiscalizador, ResultadoFiscalizacion } from '../models/solicitud.model';
import { environment } from '../../environments/environment';

// Coordenadas del distrito de San Miguel, Lima (centro aproximado distrital).
export const MUNICIPALIDAD_SAN_MIGUEL_COORDS: [number, number] = [-12.077261, -77.092869];
interface SolicitudPayload extends Partial<Solicitud> {}
export interface ProgramacionDia { codigo: string; horaFiscalizacion: string; ciudadano: string; fiscalizador: string; estado: string; }
export interface FiscalizadorTarea { codigo:string; ciudadano:string; dni:string; telefono:string; direccion:string; referencia:string; fecha:string; hora:string; latitud:number; longitud:number; documento:string; resultado:'PENDIENTE'|'REALIZADA'|'NO_REALIZADA'; observaciones?:string; observacionesFiscalizador?:string; observacionesMunicipales?:string; reporteNombreOriginal?:string; reporteTamano?:number; fechaEjecucion?:string; estadoSolicitud:string; esExpediente?:boolean; objetoFiscalizacion?:string; estadoProgramacion?:string; tipoVisita?:string; origen?:string; programacionId?:number; diligenciaId?:number|null; estadoDiligencia?:string|null; }
export interface TareaExpedienteCampo { codigo:string; objetoFiscalizacion:string; administrado:string|null; documentoAdministrado:string|null; telefono:string|null; direccion:string|null; referencia:string|null; fecha:string; hora:string; latitud:number|null; longitud:number|null; origen:string; tipoVisita:string; estadoProgramacion:string; estadoExpediente:string; programacionId:number; diligenciaId:number|null; estadoDiligencia:string|null; solicitudCodigo?:string|null; }
export interface ProgramacionExpediente { id:number; fecha:string|null; hora:string|null; tipoVisita:string; estado:string; fiscalizadorId:string|null; fiscalizadorNombre:string|null; programacionAnteriorId:number|null; motivoReprogramacion:string|null; motivoCancelacion:string|null; motivoSeguimiento?:string|null; revisionOrigenId?:number|null; }
export interface HistorialExpediente { fechaHora:string; actor:string|null; tipoEvento:string; descripcion:string; valoresAnteriores:string|null; valoresNuevos:string|null; programacionId:number|null; }
export interface Expediente { id:number; codigo:string; fechaCreacion:string; creadoPor:string|null; origen:string; detalleOrigen:string|null; estado:string; objetoFiscalizacion:string; observacionesIniciales:string|null; solicitudCodigo:string|null; tipoAdministrado:string|null; documentoAdministrado:string|null; nombreAdministrado:string|null; telefonoContacto:string|null; direccionFiscalizada:string|null; administradoApellidos:string|null; referenciaDomicilio:string|null; latitud:number|null; longitud:number|null; documentoSustentoNombre:string|null; documentoSustentoFecha:string|null; reporteFiscalizadorNombre:string|null; programaciones:ProgramacionExpediente[]; historial:HistorialExpediente[]; }
export interface DiligenciaParticipante { id:number; tipoParticipante:string; nombre:string; apellidos:string|null; tipoDocumento:string|null; numeroDocumento:string|null; entidadArea:string|null; cargoCondicion:string|null; observaciones:string|null; creadoEn:string; creadoPor:string|null; }
export interface EvidenciaDiligencia { id:number; tipo:string; nombreOriginal:string; tipoMime:string; tamanoBytes:number; descripcion:string|null; fechaHora:string; autor:string|null; }
export interface ActaFiscalizacion { id:number; codigo:string; diligenciaId:number; expedienteCodigo:string; firmaFiscalizadoEstado:string; firmaFiscalizadoObservacion:string|null; pdfGeneradoNombre:string; pdfFirmadoNombre:string|null; generadoEn:string; contenido:Record<string,unknown>; }
export interface DiligenciaWorkspace { id:number|null; expedienteCodigo:string; origen:string; objetoFiscalizacion:string; observacionesPrevias:string|null; administradoNombre:string; documentoAdministrado:string|null; telefonoContacto:string|null; direccion:string|null; referencia:string|null; latitudPredio:number|null; longitudPredio:number|null; programacionId:number; fechaProgramada:string; horaProgramada:string; tipoVisita:string; estadoProgramacion:string; estadoExpediente:string; estadoDiligencia:string|null; fechaInicio:string|null; fechaCierre:string|null; latitudInicio:number|null; longitudInicio:number|null; gpsInicioEstado:string|null; latitudCierre:number|null; longitudCierre:number|null; gpsCierreEstado:string|null; lugarDiligencia:string|null; situacionPersona:string|null; personaNombres:string|null; personaApellidos:string|null; personaTipoDocumento:string|null; personaNumeroDocumento:string|null; personaCondicion:string|null; personaObservaciones:string|null; hechosConstatados:string|null; ocurrencias:string|null; observacionesFiscalizador:string|null; observacionesFiscalizado:string|null; motivoNoRealizada:string|null; detalleMotivoNoRealizada:string|null; copiaEntregada:boolean; medioEntrega:string|null; documentoSustentoNombre:string|null; participantes:DiligenciaParticipante[]; evidencias:EvidenciaDiligencia[]; acta:Pick<ActaFiscalizacion,'id'|'codigo'|'firmaFiscalizadoEstado'|'pdfGeneradoNombre'|'pdfFirmadoNombre'|'generadoEn'>|null; }

@Injectable({ providedIn: 'root' })
export class VerificacionService {
  private cache: Solicitud[] = [];
  private archivoPendiente: File | null = null;
  private readonly base = `${environment.apiUrl}/api`;
  constructor(private http: HttpClient) {}
  guardarArchivoPendiente(file: File | null): void { this.archivoPendiente = file; }
  obtenerArchivoPendiente(): File | null { return this.archivoPendiente; }
  limpiarArchivoPendiente(): void { this.archivoPendiente = null; }
  async obtenerSolicitudes(params?: { q?: string; estado?: string; fecha?: string; fiscalizadorId?: string }): Promise<Solicitud[]> { let p=new HttpParams();Object.entries(params??{}).forEach(([k,v])=>{if(v)p=p.set(k,v);});this.cache=await firstValueFrom(this.http.get<Solicitud[]>(`${this.base}/solicitudes`,{params:p}));return this.cache; }
  programacion$(fecha: string): Observable<ProgramacionDia[]> { return this.http.get<ProgramacionDia[]>(`${this.base}/solicitudes/programacion`, { params: { fecha } }); }
  async listarExpedientes(): Promise<Expediente[]> { return firstValueFrom(this.http.get<Expediente[]>(`${this.base}/expedientes`)); }
  async obtenerExpediente(codigo:string):Promise<Expediente>{return firstValueFrom(this.http.get<Expediente>(`${this.base}/expedientes/${encodeURIComponent(codigo)}`));}
  async crearExpediente(datos:Record<string,unknown>):Promise<Expediente>{return firstValueFrom(this.http.post<Expediente>(`${this.base}/expedientes`,datos));}
  async programarExpediente(codigo:string,datos:Record<string,unknown>):Promise<ProgramacionExpediente>{return firstValueFrom(this.http.post<ProgramacionExpediente>(`${this.base}/expedientes/${encodeURIComponent(codigo)}/programaciones`,datos));}
  async reprogramar(id:number,datos:Record<string,unknown>):Promise<ProgramacionExpediente>{return firstValueFrom(this.http.post<ProgramacionExpediente>(`${this.base}/programaciones/${id}/reprogramar`,datos));}
  async cancelarProgramacion(id:number,motivo:string):Promise<ProgramacionExpediente>{return firstValueFrom(this.http.post<ProgramacionExpediente>(`${this.base}/programaciones/${id}/cancelar`,{motivo}));}
  async adjuntarSustento(codigo:string,file:File):Promise<Expediente>{const f=new FormData();f.append('documento',file,file.name);return firstValueFrom(this.http.post<Expediente>(`${this.base}/expedientes/${encodeURIComponent(codigo)}/documento`,f));}
  async abrirSustento(codigo:string):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/expedientes/${encodeURIComponent(codigo)}/documento`,{responseType:'blob'}));}
  async obtenerFiscalizadores(): Promise<Fiscalizador[]> { return firstValueFrom(this.http.get<Fiscalizador[]>(`${this.base}/catalogos/fiscalizadores`)); }
  async obtenerMisTareas(fecha?: string): Promise<FiscalizadorTarea[]> { let p=new HttpParams(); if(fecha)p=p.set('fecha',fecha); return firstValueFrom(this.http.get<FiscalizadorTarea[]>(`${this.base}/fiscalizador/mis-tareas`,{params:p})); }
  async obtenerMisProximas(): Promise<FiscalizadorTarea[]> { return firstValueFrom(this.http.get<FiscalizadorTarea[]>(`${this.base}/fiscalizador/mis-tareas/proximas`)); }
  async obtenerMisExpedientesCampo(): Promise<TareaExpedienteCampo[]> { return firstValueFrom(this.http.get<TareaExpedienteCampo[]>(`${this.base}/fiscalizador/mis-expedientes`)); }
  async obtenerEspacioDiligencia(programacionId:number):Promise<DiligenciaWorkspace>{return firstValueFrom(this.http.get<DiligenciaWorkspace>(`${this.base}/fiscalizador/programaciones/${programacionId}/diligencia`));}
  async iniciarDiligencia(programacionId:number,gps:Record<string,unknown>):Promise<DiligenciaWorkspace>{return firstValueFrom(this.http.post<DiligenciaWorkspace>(`${this.base}/fiscalizador/programaciones/${programacionId}/diligencia/iniciar`,gps));}
  async guardarDiligencia(id:number,data:Record<string,unknown>):Promise<DiligenciaWorkspace>{return firstValueFrom(this.http.patch<DiligenciaWorkspace>(`${this.base}/fiscalizador/diligencias/${id}`,data));}
  async agregarParticipanteDiligencia(id:number,data:Record<string,unknown>):Promise<DiligenciaParticipante>{return firstValueFrom(this.http.post<DiligenciaParticipante>(`${this.base}/fiscalizador/diligencias/${id}/participantes`,data));}
  async agregarEvidenciaDiligencia(id:number,tipo:string,descripcion:string,file:File):Promise<EvidenciaDiligencia>{const form=new FormData();form.append('tipo',tipo);if(descripcion)form.append('descripcion',descripcion);form.append('archivo',file,file.name);return firstValueFrom(this.http.post<EvidenciaDiligencia>(`${this.base}/fiscalizador/diligencias/${id}/evidencias`,form));}
  async evidenciaDiligencia(id:number,evidenciaId:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/fiscalizador/diligencias/${id}/evidencias/${evidenciaId}/archivo`,{responseType:'blob'}));}
  async documentoSustentoProgramacion(programacionId:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/fiscalizador/programaciones/${programacionId}/documento-sustento`,{responseType:'blob'}));}
  async finalizarDiligencia(id:number,data:Record<string,unknown>):Promise<ActaFiscalizacion>{return firstValueFrom(this.http.post<ActaFiscalizacion>(`${this.base}/fiscalizador/diligencias/${id}/finalizar`,data));}
  async noRealizadaDiligencia(programacionId:number,data:Record<string,unknown>):Promise<DiligenciaWorkspace>{return firstValueFrom(this.http.post<DiligenciaWorkspace>(`${this.base}/fiscalizador/programaciones/${programacionId}/diligencia/no-realizada`,data));}
  async actasExpediente(codigo:string):Promise<ActaFiscalizacion[]>{return firstValueFrom(this.http.get<ActaFiscalizacion[]>(`${this.base}/actas/expediente/${encodeURIComponent(codigo)}`));}
  async descargarActa(id:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/actas/${id}/pdf`,{responseType:'blob'}));}
  async descargarCopiaFirmadaActa(id:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/actas/${id}/copia-firmada`,{responseType:'blob'}));}
  async subirCopiaFirmadaActa(id:number,file:File):Promise<ActaFiscalizacion>{const f=new FormData();f.append('archivo',file,file.name);return firstValueFrom(this.http.post<ActaFiscalizacion>(`${this.base}/actas/${id}/copia-firmada`,f));}
  async evidenciaActa(id:number,evidenciaId:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/actas/${id}/evidencias/${evidenciaId}`,{responseType:'blob'}));}
  async revisionesPendientes():Promise<any[]>{return firstValueFrom(this.http.get<any[]>(`${this.base}/revisiones/pendientes`));}
  async iniciarRevision(diligenciaId:number):Promise<any>{return firstValueFrom(this.http.post<any>(`${this.base}/revisiones/diligencias/${diligenciaId}/iniciar`,{}));}
  async revision(id:number):Promise<any>{return firstValueFrom(this.http.get<any>(`${this.base}/revisiones/${id}`));}
  async ciclosFiscalizacion(codigo:string):Promise<any>{return firstValueFrom(this.http.get<any>(`${this.base}/revisiones/expediente/${encodeURIComponent(codigo)}`));}
  async solicitarAclaracion(id:number,mensaje:string):Promise<any>{return firstValueFrom(this.http.post<any>(`${this.base}/revisiones/${id}/aclaraciones`,{mensaje}));}
  async misAclaraciones():Promise<any[]>{return firstValueFrom(this.http.get<any[]>(`${this.base}/revisiones/mis-aclaraciones`));}
  async responderAclaracion(id:number,respuesta:string):Promise<any>{return firstValueFrom(this.http.post<any>(`${this.base}/revisiones/aclaraciones/${id}/responder`,{respuesta}));}
  async concluirRevision(id:number,body:Record<string,unknown>):Promise<any>{return firstValueFrom(this.http.post<any>(`${this.base}/revisiones/${id}/concluir`,body));}
  async crearSeguimiento(id:number,body:Record<string,unknown>):Promise<any>{return firstValueFrom(this.http.post<any>(`${this.base}/revisiones/${id}/seguimientos`,body));}
  async descargarInformeConclusion(id:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/revisiones/${id}/informe.pdf`,{responseType:'blob'}));}
  async evidenciaRevision(diligenciaId:number,evidenciaId:number):Promise<Blob>{return firstValueFrom(this.http.get(`${this.base}/revisiones/diligencias/${diligenciaId}/evidencias/${evidenciaId}`,{responseType:'blob'}));}
  async obtenerMiHistorial(fecha?: string, resultado?: string): Promise<FiscalizadorTarea[]> { let params = new HttpParams(); if (fecha) params = params.set('fecha', fecha); if (resultado && resultado !== 'TODOS') params = params.set('resultado', resultado); return firstValueFrom(this.http.get<FiscalizadorTarea[]>(`${this.base}/fiscalizador/mis-tareas/historial`, { params })); }
  async obtenerMiTarea(codigo:string): Promise<Solicitud> { return firstValueFrom(this.http.get<Solicitud>(`${this.base}/fiscalizador/mis-tareas/${encodeURIComponent(codigo)}`)); }
  async registrarResultado(codigo:string, resultado:ResultadoFiscalizacion, observaciones:string, reporte:File|null): Promise<Solicitud> { const form=new FormData(); form.append('resultado',new Blob([JSON.stringify({resultado,observaciones})],{type:'application/json'})); if(reporte)form.append('reporte',reporte,reporte.name); return firstValueFrom(this.http.put<Solicitud>(`${this.base}/fiscalizador/mis-tareas/${encodeURIComponent(codigo)}/resultado`,form)); }
  async abrirReporte(codigo:string): Promise<Blob> { return firstValueFrom(this.http.get(`${this.base}/solicitudes/${encodeURIComponent(codigo)}/reporte`,{responseType:'blob'})); }
  async abrirDocumentoTarea(codigo:string): Promise<Blob> { return firstValueFrom(this.http.get(`${this.base}/fiscalizador/mis-tareas/${encodeURIComponent(codigo)}/documento`,{responseType:'blob'})); }
  async abrirReporteTarea(codigo:string): Promise<Blob> { return firstValueFrom(this.http.get(`${this.base}/fiscalizador/mis-tareas/${encodeURIComponent(codigo)}/reporte`,{responseType:'blob'})); }
  obtenerSolicitudPorCodigo(codigo: string): Solicitud|undefined { return this.cache.find(s=>s.codigo===codigo); }
  async cargarSolicitud(codigo: string): Promise<Solicitud> { const s=await firstValueFrom(this.http.get<Solicitud>(`${this.base}/solicitudes/${codigo}`));this.cache=[s,...this.cache.filter(x=>x.codigo!==codigo)];return s; }
  async guardarSolicitud(datos: SolicitudPayload, archivo?: File | null): Promise<Solicitud> { const body={dni:datos.dni,nombres:datos.nombres,apellidos:datos.apellidos,telefono:datos.telefono,direccion:datos.direccion,referencia:datos.referencia??'',documento:datos.documento??'',documentoTamano:datos.documentoTamano??'',latitud:datos.latitud,longitud:datos.longitud,fecha:datos.fecha,hora:datos.hora,fechaFiscalizacion:datos.fechaFiscalizacion||null,horaFiscalizacion:datos.horaFiscalizacion||null,fiscalizadorId:datos.fiscalizadorId??'',estado:datos.estado,observaciones:datos.observaciones??''}; const form=new FormData(); form.append('solicitud', new Blob([JSON.stringify(body)], {type:'application/json'})); if (archivo) form.append('documento', archivo, archivo.name); const url=datos.codigo?`${this.base}/solicitudes/${datos.codigo}`:`${this.base}/solicitudes`; const request=datos.codigo?this.http.put<Solicitud>(url,form):this.http.post<Solicitud>(url,form);const result=await firstValueFrom(request);this.cache=[result,...this.cache.filter(x=>x.codigo!==result.codigo)];return result; }
  async cambiarEstado(codigo:string,estado:EstadoSolicitud|string,resultado?:string,observacionAdicional?:string):Promise<boolean>{await firstValueFrom(this.http.patch(`${this.base}/solicitudes/${codigo}/estado`,{estado,resultado,observacionAdicional}));await this.obtenerSolicitudes();return true;}
  async abrirDocumento(codigo: string): Promise<Blob> { return firstValueFrom(this.http.get(`${this.base}/solicitudes/${encodeURIComponent(codigo)}/documento`, { responseType: 'blob' })); }
  calcularDistanciaKm(o:[number,number],d:[number,number]):number{const r=Math.PI/180,a=Math.sin((d[0]-o[0])*r/2)**2+Math.cos(o[0]*r)*Math.cos(d[0]*r)*Math.sin((d[1]-o[1])*r/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
  extraerCoordenadas(s:Solicitud):[number,number]{return[s.latitud||MUNICIPALIDAD_SAN_MIGUEL_COORDS[0],s.longitud||MUNICIPALIDAD_SAN_MIGUEL_COORDS[1]];}
  calcularMejorRuta(origen:[number,number],visitas:Solicitud[]):{orden:Solicitud[];distanciaTotalKm:number;googleMapsUrl:string}{const p=[...visitas],orden:Solicitud[]=[];let actual=origen,dist=0;while(p.length){p.sort((a,b)=>this.calcularDistanciaKm(actual,this.extraerCoordenadas(a))-this.calcularDistanciaKm(actual,this.extraerCoordenadas(b)));const n=p.shift()!;dist+=this.calcularDistanciaKm(actual,this.extraerCoordenadas(n));orden.push(n);actual=this.extraerCoordenadas(n);}return{orden,distanciaTotalKm:+dist.toFixed(2),googleMapsUrl:this.construirGoogleMapsRuta(origen,orden)};}
  construirGoogleMapsRuta(o:[number,number],orden:Solicitud[]):string{if(!orden.length)return '';const origin=`${o[0]},${o[1]}`,d=orden.map(v=>{const c=this.extraerCoordenadas(v);return`${c[0]},${c[1]}`}),dest=d.at(-1)!;const w=d.slice(0,-1).join('|');return`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(dest)}${w?`&waypoints=${encodeURIComponent(w)}`:''}&travelmode=driving`;}
  construirGoogleMapsDestinoUnico(s:Solicitud):string{const c=this.extraerCoordenadas(s);return`https://www.google.com/maps/search/?api=1&query=${c[0]},${c[1]}`;}
}
